const fs = require('fs'), 
path = require('path');
const phantomZoom = 0.75;
const ssl_options = false;
const host = '192.168.100.179';
const port = 8080;
const ssl_port = 8081;
const wp_port = 8079;
const apiUrl = 'http://localhost:6016';
//const apiUrl = 'http://www.pateast.co:4095';
// const apiUrl = 'https://www.pateast.co:3016';
const clientId = 'demo';
const clientSecret = 'demo';
const basicAuth = "Basic " + Buffer.from(clientId + ':' + clientSecret).toString('base64');
module.exports = { host, port, wp_port, ssl_port, apiUrl, clientId, clientSecret, basicAuth, ssl_options, phantomZoom, sourcemap: false};
process.on('unhandledRejection', err => console.error(err));
